FROM ubuntu

RUN apt update && apt install -y curl net-tools sshuttle build-essential git golang

RUN cd /root && git clone https://github.com/vi/tcpsocks && cd tcpsocks && make && make install

RUN cd /root && git clone https://github.com/go-gost/gost.git && cd gost/cmd/gost && go build

COPY init.sh /init.sh

RUN chmod +x /init.sh

CMD [ "/init.sh" ]