name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.io/cyberpunkyc/kubernetes-sidecar-injector:latest,docker.io/cyberpunkyc/kubernetes-sidecar-injector:${{ steps.slug.outputs.sha7 }}
      -
        name: Build and push base image for injected container
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.injected
          context: .
          push: true
          tags: docker.io/cyberpunkyc/kubernetes-sidecar-injected:latest,docker.io/cyberpunkyc/kubernetes-sidecar-injected:${{ steps.slug.outputs.sha7 }}